jobs:
  - job: BuildandPush
    displayName: BuildandPush
    pool:
      vmImage: ubuntu-latest
    steps:  

      - task: UseDotNet@2
        displayName: Use Dotnet 2.1
        inputs:
          packageType: sdk
          version: 5.x
          installationPath: /home/vsts/work/1/s/dotnet

      # - task: CmdLine@2
      #   displayName: Create APIMTemplate Tool
      #   inputs:
      #     script: |
      #       dotnet new webapp -o MyWebApp --no-https -f net6.0
      #       dotnet restore
      #       dotnet pack -c Release
      #       dotnet new tool-manifestfest
      #       dotnet add package apimtemplate --version 1.0.0
      #     failOnStderr: true

      - task: CmdLine@2
        displayName: Generate ARM templates using Tool
        inputs:
          script: 'dotnet tool run apim-templates create --appInsightsInstrumentationKey $(VariableAppinsightsInstrumentationKey) --appInsightsName  $(VariableAppinsightsName) --configFile "./valid.yml" --backendurlconfigFile "./TemplateAndParameters/BackendUrlParameters.json"'          
          failOnStderr: true


      - task: AzurePowerShell@4
        displayName: Deploy template
        inputs:
          azureSubscription: #service connection
          ScriptType: InlineScript
          inline: |
            $Location = "$(location)" -replace " ",""

            $DeploymentInputs = @{
              Name                    = "$(resourceGroupForAPIMName)-master"
              Location                = "$Location"
              TemplateFile          = "mastertemplategenerated.json" 
              DeploymentDebugLogLevel = "All"
              Verbose                 = $true
              ErrorAction             = "Stop"
              TemplateParameterFile = "./TemplateAndParameters/parameters.json"
            }
            New-AzDeployment @DeploymentInputs
          azurePowerShellVersion: LatestVersion
